### PR TITLE
Add stackoverflow to \social command

### PR DESCRIPTION
**Pull request by ShadowMitia**
Same pull request as on https://github.com/xdanaux/moderncv.

Adds the stackoverlow website as an option to the `\social` command.

### CODE REVIEW

**Comment by ebb-earl-co** [comment]
@ShadowMitia I've been using moderncv for years and have tried multiple times to figure out how to add SO to the icons so kudos to you! However, when I compile from your branch it doesn't appear in the header... Does it work for you as this PR reflects?

**Comment by ShadowMitia** [comment]
@ebb-earl-co I admit I didn't test it when I made the pull request here... I just retook what I did on the other repo. I guess something broke in the meantime...

**Comment by ShadowMitia** [comment]
@ebb-earl-co Can you test if it works for you using https://github.com/xdanaux/moderncv/pull/55 ?

Basically you need to change in template.tex

`\documentclass[11pt,a4paper,sans]{moderncv} ` to `\documentclass[11pt,a4paper,sans]{../moderncv} `

In my case not all logos appear, but you might have more luck. At least all the information that should be shown does appear!

**Comment by ShadowMitia** [comment]
Ok I've found the fix, you need #14 to have all info and logos show up properly. This branch requires #14 to be merged first.

**Comment by ShadowMitia** [comment]
@ebb-earl-co Does it work if you add the workaround?

**Comment by stephanlachnit** [comment]
Sorry for not responding - I didn't follow the conversations and wasn't notified about the PR. Will test it ASAP.

@ShadowMitia would you look like to join the project? Your PRs look good, I would give you access.

**Comment by stephanlachnit** [comment]
Tested, thanks.

**Comment by ShadowMitia** [comment]
You're welcome!
I don't mind joining the project if you think I can help, but I have very very limited experience in LaTeX though :grin: 
I'm just glad my changes will have a chance to be used easily by more people.

**Comment by stephanlachnit** [comment]
> You're welcome!
> I don't mind joining the project if you think I can help, but I have very very limited experience in LaTeX though grin
> I'm just glad my changes will have a chance to be used easily by more people.

Same here, I'm definitely not a LaTeX expert, so any help I get is important.

**Pull request merged**
