### PR TITLE
Allow icons in classic letter

### PR DESCRIPTION
**Pull request by thecaligarmo**
This fixes the bug found in:

https://github.com/moderncv/moderncv/issues/170

### CODE REVIEW

**Review by LLdaniel — COMMENTED** [review]
Nice, looks good to me for the classic style.

Do you think due to symmetry reasons we should also introduce the social icons for the "banking" and "fancy" style letters?
"oldstyle" and "casual" already include the social icons in their letter. 

Or is this a distinction addressing the variable styles and "banking" and "fancy" styles offer no additional social items on purpose in their letter?

**Review by jalopezg-git — COMMENTED** [review]
The change LGTM :+1:, but I think that, for the sake of consistency between different styles, we need to apply it also for the other `moderncvheadXXX.sty` files.

**Comment by thecaligarmo** [comment]
Sounds good. I've added it for banking/fancy as well. They look good now.

One thing I noticed is that the symbols used for `oldstyle` are the `marvosym` symbols whereas all the other ones use `symbols`. What this means is that for `oldstyle` no symbols appear for the socials.

**Comment by LLdaniel** [comment]
> Sounds good. I've added it for banking/fancy as well. They look good now.

Thanks for adding the symbols also for the other styles, @thecaligarmo !
Sorry to bother you again, but would you mind to write a short notice in our `CHANGELOG` as well? That would be great!
Something like 
```text
- include social icons in cover letter for styles classic, fancy and banking (#170)
```


> One thing I noticed is that the symbols used for oldstyle are the marvosym symbols whereas all the other ones use symbols. What this means is that for oldstyle no symbols appear for the socials.

Oh, interesting. Did you use `pdflatex`?
It comes from here, you are right:
https://github.com/moderncv/moderncv/blob/cdf027a9da1f16038c2df3c02147b3b316741dac/moderncvstyleoldstyle.sty#L48-L57

In my opinion it line 51 should be at least `\moderncvicons{symbols}`. Maybe line 53 should be changed to that too.
But I think we should cover this in a separate issue.

**Comment by thecaligarmo** [comment]
Yes, I used pdflatex. Yeah, I don't know why that choice was made. If it needs to be changed, you can make another ticket and assign it to me. I can do it fairly fast. 

Changelog has been updated as requested.

**Review by LLdaniel — APPROVED** [review]
Thank you! :partying_face:

**Pull request merged**
