### PR TITLE
Add the possibility to add a subject line in the letter

### LINKED ISSUE #113: No way to specify a subject line in the cover letter
I wonder if anyone is using the cover letter feature, as template.tex puts it after the CV, and I believe it should be before the CV in the PDF. This can easily be solved by moving things around (I can send a PR for the template.tex if you like).

But for me, it would be necessary to be able to specify a subject line. There are a couple of suggestions floating around, on [launchpad](https://answers.launchpad.net/moderncv/+question/222784) and [stackexchange](https://tex.stackexchange.com/questions/328056/add-the-field-subject-to-moderncv-letter). What do you think?

### PR DESCRIPTION
**Pull request by jranke**
This is simply the suggestion given by Matthias Baur on launchpad
https://answers.launchpad.net/moderncv/+question/222784 in comment 12
Closes #113

It works well for my purposes and looks decent. Maybe the spacing before the subject line could be bigger, let me know what you think.

### CODE REVIEW

**Comment by mefuller** [comment]
Looks good to me - @jranke would you squash to one commit and rebase?

**Review by mefuller — APPROVED** [review]

**Comment by jranke** [comment]
OK, sure, I squashed the two commits to one, the branch is already based on the latest commit of your master branch.

**Review by stephanlachnit — CHANGES_REQUESTED** [review]
LGTM, but could you add a subject to the template? Then we can merge it.

**Comment by jranke** [comment]
Yes, good idea! Will do so in a minute

**Pull request merged**
