### PR TITLE
Make colors user adjustable. expose hidden head options in all styles.

### PR DESCRIPTION
**Pull request by cryptointerest**
- Systematize colors and make them user adjustable. See documentation for details.
  this requires the \moderncvcolor to be issued BEFORE \moderncvstyle.
- all styles: make the head options 'details' and 'nodetails' available to the user.
(previously they were hidden). Olystyle does not respond too well to nodetails.

### CODE REVIEW

**Comment by mefuller** [comment]
@cryptointerest also here: is this PR ready for review (nominally final)?

**Comment by cryptointerest** [comment]
> @cryptointerest also here: is this PR ready for review (nominally final)?

@mefuller Yes.

**Comment by mefuller** [comment]
OK, great. I'll try to sit down and figure out whether/how these can be merged still and get them reviewed

**Comment by mefuller** [comment]
I think the original commit here should really be broken into three commits, and actually two separate PRs given the current state:

1.  all styles: make the head options 'details' and 'nodetails' available to the user.

2. Colors (two commits):
    - Systematize colors and make them user adjustable. 
    - Updated docs

Once that's done, I anticipate the first PR can be merged fairly easily while the colors looks like a much more time-consuming task

**Comment by cryptointerest** [comment]
mhh, yeah, that's a similar criticism than for all my PRs. At the time it seemed a good idea to bundle certain changes together as I was not too experienced with a PR based work flow and exposing hidden options came along with changes to the user guide that I was writing. 
Since if I remember correctly commits are not clean in the sense that each change (code, user guide) got committed separately, this means undoing commits and restructuring them into new commits on a line by line basis. Extremely tedious.

As I mentioned, due to health reasons, I will definitely not do this and for an indefinite time (i.e. until I'm completely healed, which, as of now, does not seem to happen).

**Comment by mefuller** [comment]
Closing as all changes incorporated into restructured PRs #150 and #151

**Pull request closed without merging**
