### PR TITLE
Added gitlabsocialsymbol

### PR DESCRIPTION
**Pull request by gcorrad**
I added the GitLab social icon

### CODE REVIEW

**Comment by ShadowMitia** [comment]
Should help with #26.

**Comment by gcorrad** [comment]
> I did not know it existed, just google and found in gitlab media an svg to convert to tickzpicture. Just today I figure it. If it's okay with you, I try to convert one of those and make another pull request.

**Comment by stephanlachnit** [comment]
Ok so after reading #81, it actually seems better to fix #81 instead of adding icons in converted form. But I don't really have time to fix this until at least February (due to exams).

Since I highly doubt there will be a new release until then, I would leave this PR as is and close it when #81 is fixed. Thanks anyway.

**Comment by gcorrad** [comment]
My mistake, i will open another pr

**Pull request closed without merging**
