### PR TITLE
make hidden head options available in casual style

### PR DESCRIPTION
**Pull request by cryptointerest**
casual style: make the head options 'alternate', 'details' and
'nodetails' available to the user. (previously they were hidden).

### CODE REVIEW

**Comment by mefuller** [comment]
@cryptointerest was this PR intended to be ready for review?

**Comment by cryptointerest** [comment]
> @cryptointerest was this PR intended to be ready for review?

@mefuller Yes,  same as the other one, it was when I submitted the PR. I haven't checked it with recent changes and can't work on it due to my inflamations being rather finely maintained by my day job (yes, it has been two years).

**Comment by mefuller** [comment]
[current_master_casual_20230127.pdf](https://github.com/moderncv/moderncv/files/10517442/current_master_casual_20230127.pdf)
[pr55_casual.pdf](https://github.com/moderncv/moderncv/files/10517443/pr55_casual.pdf)
[pr55_casual_alternate.pdf](https://github.com/moderncv/moderncv/files/10517444/pr55_casual_alternate.pdf)
[pr55_casual_details.pdf](https://github.com/moderncv/moderncv/files/10517445/pr55_casual_details.pdf)

Hi all,
attached are outputs from the current master, then toggling the three options (default is nodetails).
I think this is ready to go, but would appreciate one other quick look and approval

**Review by mefuller — APPROVED** [review]

**Comment by mefuller** [comment]
close in favor of #150

**Pull request closed without merging**
