### PR TITLE
Update user guide

### LINKED ISSUE #168: Consider creating a new tag (last tag is more than a year old)
Hello,

TeXLive currently offers the moderncv class from 2022-02-21 (v. 2.3.1).
Looking at CTAN, same result: https://ctan.org/pkg/moderncv?lang=en

The reason: looking for the available tags here in the repo shows me, there is no newer tag avaialable.

So, to have a more recent class available via TeXLive & Co., please consider adding a new tag.

### PR DESCRIPTION
**Pull request by tianyizheng02**
Contributes to #106, fixes #168

Rebased work done by @cryptointerest in #58 to be up to date with the past two years of commits made to this repo. I may have lost some additions made in #58 while resolving merge conflicts, so I strongly encourage everyone to carefully read through the updated files and point out any typos, errors, or inconsistencies.

In particular, do check out the changelog file and the known errors section of the user guide. I'm not sure if those are completely up to date and accurate.

### CODE REVIEW

**Comment by tianyizheng02** [comment]
Restructured the README because the makefile from #54 hasn't been added yet

**Comment by tianyizheng02** [comment]
@mefuller @stephanlachnit The user guide is still incomplete, but I'd appreciate it if you could review it anyway along with the changelog

**Comment by stephanlachnit** [comment]
Thanks a lot! From my side, we can merge this. We should probably add this to our CI, but you don't have to do that in this PR.

**Review by stephanlachnit — APPROVED** [review]
LGTM

**Comment by stephanlachnit** [comment]
> In particular, do check out the changelog file and the known errors section of the user guide. I'm not sure if those are completely up to date and accurate.

I don't see the CHANGELOG file being modified? This would be required for #168.

**Comment by tianyizheng02** [comment]
> I don't see the CHANGELOG file being modified? This would be required for #168.

That's my bad, I forgot to actually update the CHANGELOG in this draft PR. Right now I have it updated in my local repo with just a list of the PRs merged since the last tag; is that sufficient? Also, what would this next version be? 2.4.0? 2.3.2?

**Comment by stephanlachnit** [comment]
> Right now I have it updated in my local repo with just a list of the PRs merged since the last tag; is that sufficient? Also, what would this next version be? 2.4.0? 2.3.2?

Yes, should be. I try to follow semantic versioning (https://semver.org/), so the next version would be `2.4.0`.

Thanks a lot! I will try to find some time on the weekend to add some finishing touches (CI for the user guide and update release script to build manual) and upload it CTAN.

**Comment by tianyizheng02** [comment]
@stephanlachnit Any updates on the new version tag?

**Comment by tianyizheng02** [comment]
@stephanlachnit?

**Pull request merged**
